AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  gc03_check_iam_cloudwatch_alarms

Globals:
  Function:
    Timeout: 180
    MemorySize: 128

Resources:
  GC03CheckIAMCloudWatchAlarmsLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
