AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  gc06_check_encryption_at_rest_part2

Globals:
  Function:
    Timeout: 600
    MemorySize: 128

Resources:
  GC06CheckEncryptionAtRestPart2Lambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
