AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  bucket-watcher

Globals:
  Function:
    Timeout: 30
    MemorySize: 128

Resources:
  BucketWatcherLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
